# -*- coding: utf-8 -*-
"""Prueba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bDkwOB6lx6fLWl-FuV7GUZU6LZA5Tsd

# Librerías
"""

import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

file = 'data1.csv'

Nombres_Var = ['Estudiante', 'Carné', 'Sociales', 'Matemáticas', 'Música', 'Promedio']


def get_csv_data_and_fieldnames(file_path):
    """CSV"""
    existing_data = []
    current_fieldnames = list(Nombres_Var[:2])

    try:
        with open(file_path, 'r', newline='') as csvfile_read:
            reader = csv.DictReader(csvfile_read)
            if reader.fieldnames:
                current_fieldnames = reader.fieldnames
            for row in reader:
                existing_data.append(row)
    except FileNotFoundError:
        print(f"File '{file_path}' not found.")
        current_fieldnames = Nombres_var

    return existing_data, current_fieldnames


def menu():
    print("------------------------------------------------------------")
    print("Bienvenido, ¿qué deseas hacer el día de hoy?: ")
    print("1. Ver estudiantes.")
    print("2. Agregar a estudiante")
    print("3. Modificar o agregar notas")
    print("4. Ver notas de cierto estudiante.")
    print("5. Salir del programa y guardar datos")

    print("Menú:")
    while True:
      opciones = input("Ingrese la opción que desea: ")

      if opciones == "1":
        existing_data, current_fieldnames = get_csv_data_and_fieldnames(file)
        if not existing_data:
            print("No hay estudiantes en la lista.")
        else:
            print("Estudiantes:")
            for row in existing_data:
                print(f"{row.get('Estudiante', 'N/A')} (Carné: {row.get('Carné', 'N/A')})")

      elif opciones == "2":
          estudiante = input("Estudiante: ")
          carnet = input("Carnet: ")

          existing_data, current_fieldnames = get_csv_data_and_fieldnames(file)

          student_exists = False
          for row in existing_data:
              if row.get('Estudiante') == estudiante and row.get('Carné') == carnet:
                  student_exists = True
                  break

          if not student_exists:
            new_student_data = {'Estudiante': estudiante, 'Carné': carnet}
            new_student_row = {field: new_student_data_input.get(field, '') for field in current_fieldnames}

            existing_data.append(new_student_row)
            with open(file, 'w', newline='') as csvfile_write:
              writer = csv.DictWriter(csvfile_write, fieldnames=current_fieldnames)
              writer.writeheader()
              writer.writerows(existing_data)
            print(f"Estudiante '{estudiante}' agregado exitosamente.")

          else:
              print("El estudiante y/o Carnet ya existe")



      elif opciones == "3":
          existing_data, current_fieldnames = get_csv_data_and_fieldnames(file)

          # Corrected 'Mósica' to 'Música' and ensure Promedio is considered
          new_grade_fields = ["Sociales", "Matemáticas", "Música", "Promedio"]
          for field in new_grade_fields:
              if field not in current_fieldnames:
                  current_fieldnames.append(field)

          estudiante_to_modify = input("Ingrese el nombre del estudiante para modificar/agregar notas: ")
          carnet_to_modify = input("Ingrese el carné del estudiante para modificar/agregar notas: ")

          student_found = False
          for student_row in existing_data:
              if student_row.get('Estudiante') == estudiante_to_modify and student_row.get('Carné') == carnet_to_modify:
                  student_found = True
                  Sociales = float(input("Ingrese la nota de Ciencias Sociales: "))
                  Matemáticas = float(input("Ingrese la nota de Matemáticas: "))
                  Música = float(input("Ingrese la nota de Música: ")) # Corrected typo

                  Promedio = (Sociales + Matemáticas + Música) / 3 # Corrected typo

                  student_row['Sociales'] = Sociales
                  student_row['Matemáticas'] = Matemáticas
                  student_row['Música'] = Música # Corrected typo
                  student_row['Promedio'] = Promedio
                  break

          if student_found:
              with open(file, 'w', newline='') as csvfile_write:
                  writer = csv.DictWriter(csvfile_write, fieldnames=current_fieldnames)
                  writer.writeheader()
                  writer.writerows(existing_data)
              print(f"Notas modificadas/agregadas para {estudiante_to_modify}.")
          else:
              print("Estudiante no encontrado. Por favor, ingrese un nombre de estudiante y un carné válidos.")

      elif opciones == "4": # Ver notas de cierto estudiante
        existing_data, current_fieldnames = get_csv_data_and_fieldnames(file)

        input_student = input("Ingrese el nombre del estudiante para ver sus notas: ")
        input_carnet = input("Ingrese el carné del estudiante para ver sus notas: ")

        student_found_in_data = False
        grades_displayed = False
        for row in existing_data:
            if row.get('Estudiante') == input_student and row.get('Carné') == input_carnet:
                student_found_in_data = True
                print(f"Las notas y promedio del estudiante {input_student} ({input_carnet}) son: ")
                grade_fields = [field for field in Nombres_var if field not in ['Estudiante', 'Carné']]
                for field in grade_fields:
                    if field in row and row[field] != '' and row[field] is not None:
                        print(f"{field}: {row[field]}")
                        grades_displayed = True
                break

        if student_found_in_data and not grades_displayed:
            print("El estudiante no tiene notas registradas.")
        elif not student_found_in_data:
            print("No se encontraron notas para el estudiante o el estudiante no existe.")

      elif opciones =="5":
          print("Guardando y saliendo")
          break
      else:
          print("Opción no válida, intente de nuevo.")

menu()